/*
 * hgemm_16warp_aligned.cu — variant of hgemm_16warp with boundary checks
 * dropped. Assumes M, N, K are exact multiples of BM=128, BN=128, BK=32.
 *
 * Hypothesis: NCU on hgemm_16warp showed `stall_math_throttle = 35.46`.
 * Cubin instruction histogram showed 139 IMAD vs 32 HMMA. The IMAD chain
 * is dominated by predicated branches (@P0..@P6) generated by the LOAD_*
 * macro fallbacks for partial tiles. Removing the branches collapses the
 * predicated address arithmetic into a single straight-line block,
 * cutting the IMAD count and freeing the integer pipe to keep up with
 * HMMA issue.
 *
 * If the hypothesis is right, expect:
 *   IMAD count drops sharply (target: < 80 from 139)
 *   stall_math_throttle drops below 10 (from 35.46)
 *   TC util rises above 60% (from 46.3%)
 *   GFLOPS rises proportionally
 *
 * Build:
 *   nvcc --cubin -arch=sm_86 -O2 -o hgemm_16warp_aligned.sm_86.cubin \
 *        hgemm_16warp_aligned.cu
 */

#include <mma.h>
#include <cuda_fp16.h>
#include <cuda_pipeline.h>
using namespace nvcuda;

#define WMMA_M 16
#define WMMA_N 16
#define WMMA_K 16

#define BM 128
#define BN 128
#define BK 32

#define PAD_A    8
#define PAD_B    8
#define STRIDE_A (BK + PAD_A)
#define STRIDE_B (BN + PAD_B)

#define NUM_WARPS   16
#define WARP_SIZE   32
#define BLOCK_SIZE  (NUM_WARPS * WARP_SIZE)

#define WARPS_Y 4
#define WARPS_X 4
#define WARP_TILES_M 2
#define WARP_TILES_N 2

#define CP_ASYNC_BYTES  16
#define ELEMS_PER_COPY  (CP_ASYNC_BYTES / 2)
#define CP_ELEMS_A      (BM * BK / BLOCK_SIZE * 2 / CP_ASYNC_BYTES)
#define CP_ELEMS_B      (BK * BN / BLOCK_SIZE * 2 / CP_ASYNC_BYTES)

extern "C" __global__ __launch_bounds__(BLOCK_SIZE, 2)
void hgemm_16warp_aligned(
    const __half * __restrict__ matrix_a,
    const __half * __restrict__ matrix_b,
    float        * __restrict__ matrix_c,
    int M, int N, int K
) {
    __shared__ __align__(16) __half smem_a[2][BM * STRIDE_A];
    __shared__ __align__(16) __half smem_b[2][BK * STRIDE_B];

    int tid     = threadIdx.x;
    int warp_id = tid / WARP_SIZE;
    int wy      = warp_id / WARPS_X;
    int wx      = warp_id % WARPS_X;

    int block_row = blockIdx.y * BM;
    int block_col = blockIdx.x * BN;

    wmma::fragment<wmma::accumulator, WMMA_M, WMMA_N, WMMA_K, float>
        acc[WARP_TILES_M][WARP_TILES_N];
    #pragma unroll
    for (int i = 0; i < WARP_TILES_M; i++)
        #pragma unroll
        for (int j = 0; j < WARP_TILES_N; j++)
            wmma::fill_fragment(acc[i][j], 0.0f);

    int num_tiles = K / BK;   // exact, by alignment precondition

    // Per-thread, per-iteration offsets (constant across outer tile loop) —
    // hoist by computing once. Note: with CP_ELEMS_A = CP_ELEMS_B = 1, the
    // unroll over _i collapses to a single iteration so the macro call
    // produces one straight-line cp.async per thread per tile.
    //
    // Dropped: the partial-tile fallback branch. Aligned-only.

    #define LOAD_A_TILE(buf, k_base)                                          \
        _Pragma("unroll")                                                     \
        for (int _i = 0; _i < CP_ELEMS_A; _i++) {                           \
            int _flat = (tid + _i * BLOCK_SIZE) * ELEMS_PER_COPY;           \
            int _row  = _flat / BK;                                          \
            int _col  = _flat % BK;                                          \
            int _soff = _row * STRIDE_A + _col;                             \
            int _grow = block_row + _row;                                    \
            int _gcol = (k_base) + _col;                                    \
            __pipeline_memcpy_async(                                          \
                &smem_a[buf][_soff],                                          \
                &matrix_a[_grow * K + _gcol],                                \
                CP_ASYNC_BYTES);                                              \
        }

    #define LOAD_B_TILE(buf, k_base)                                          \
        _Pragma("unroll")                                                     \
        for (int _i = 0; _i < CP_ELEMS_B; _i++) {                           \
            int _flat = (tid + _i * BLOCK_SIZE) * ELEMS_PER_COPY;           \
            int _row  = _flat / BN;                                          \
            int _col  = _flat % BN;                                          \
            int _soff = _row * STRIDE_B + _col;                             \
            int _grow = (k_base) + _row;                                    \
            int _gcol = block_col + _col;                                    \
            __pipeline_memcpy_async(                                          \
                &smem_b[buf][_soff],                                          \
                &matrix_b[_grow * N + _gcol],                                \
                CP_ASYNC_BYTES);                                              \
        }

    #define COMPUTE_TILE(buf)                                                  \
        _Pragma("unroll")                                                     \
        for (int k_local = 0; k_local < BK; k_local += WMMA_K) {            \
            wmma::fragment<wmma::matrix_a, WMMA_M, WMMA_N, WMMA_K,          \
                           __half, wmma::row_major> a_frag[WARP_TILES_M];   \
            _Pragma("unroll")                                                 \
            for (int wi = 0; wi < WARP_TILES_M; wi++) {                      \
                int a_row = wy * 32 + wi * WMMA_M;                           \
                wmma::load_matrix_sync(a_frag[wi],                            \
                    &smem_a[buf][a_row * STRIDE_A + k_local], STRIDE_A);     \
            }                                                                  \
            wmma::fragment<wmma::matrix_b, WMMA_M, WMMA_N, WMMA_K,          \
                           __half, wmma::row_major> b_frag[WARP_TILES_N];   \
            _Pragma("unroll")                                                 \
            for (int wj = 0; wj < WARP_TILES_N; wj++) {                      \
                int b_col = wx * 32 + wj * WMMA_N;                           \
                wmma::load_matrix_sync(b_frag[wj],                            \
                    &smem_b[buf][k_local * STRIDE_B + b_col], STRIDE_B);     \
            }                                                                  \
            _Pragma("unroll")                                                 \
            for (int wi = 0; wi < WARP_TILES_M; wi++)                         \
                _Pragma("unroll")                                             \
                for (int wj = 0; wj < WARP_TILES_N; wj++)                    \
                    wmma::mma_sync(acc[wi][wj], a_frag[wi], b_frag[wj],      \
                                   acc[wi][wj]);                              \
        }

    LOAD_A_TILE(0, 0);
    LOAD_B_TILE(0, 0);
    __pipeline_commit();
    __pipeline_wait_prior(0);
    __syncthreads();

    for (int tile = 0; tile < num_tiles - 1; tile++) {
        int next_k_base = (tile + 1) * BK;
        int cur_buf     = tile & 1;
        int next_buf    = 1 - cur_buf;

        LOAD_A_TILE(next_buf, next_k_base);
        LOAD_B_TILE(next_buf, next_k_base);
        __pipeline_commit();
        COMPUTE_TILE(cur_buf);
        __pipeline_wait_prior(0);
        __syncthreads();
    }

    {
        int last_buf = (num_tiles - 1) & 1;
        COMPUTE_TILE(last_buf);
    }

    #undef LOAD_A_TILE
    #undef LOAD_B_TILE
    #undef COMPUTE_TILE

    #pragma unroll
    for (int wi = 0; wi < WARP_TILES_M; wi++) {
        #pragma unroll
        for (int wj = 0; wj < WARP_TILES_N; wj++) {
            int c_row = block_row + wy * 32 + wi * WMMA_M;
            int c_col = block_col + wx * 32 + wj * WMMA_N;
            wmma::store_matrix_sync(
                &matrix_c[c_row * N + c_col],
                acc[wi][wj], N, wmma::mem_row_major);
        }
    }
}
